name: DeathSpectating
author: RoboMWM
version: ${project.version}
main: to.us.tf.DeathSpectating.DeathSpectating
permissions:
    deathspectating.*:
        description: Grants ALL THE THINGS
        children:
            deathspectating.allow: true
            deathspectating.teleport: true
    deathspectating.allow:
        description: Permission to enter death spectating mode. Permission has no effect if not enabled in config.
        default: false
    deathspectating.teleport:
        description: Permission to teleport while death spectating.
        default: false
